add support for preview images in list views
526avijitgupta/gokarna pull request #151
Opened 2023-01-01 16:44 UTC by azplanlos

I don't know if this small improvement is of interest for anyone else except me, but I added an option to include preview images in list views. By default every posts first image is taken as preview image and resized to a smaller size. If no image is present a feather icon can be used. Also in this PR taxonomy pages use the correct title as title instead of the hard coded title "Tags".

2023-01-09 15:20 UTC, yashmehrotra requested changes

2023-01-09 15:20 UTC, yashmehrotra commented on exampleSite/config.toml
> +  ShowPreviewImages = "false"
Please use boolean type not string

2023-01-09 15:20 UTC, yashmehrotra commented on exampleSite/config.toml
> +  ShowPreviewImages = "false"
Also, use smaller case and change variable to `enablePreviewImages`

2023-01-09 15:22 UTC, yashmehrotra commented
@azplanlos Hey, when I tried this on my local, this was not working as expected and the images were not showing up

Can you update your PR with the param as true in the `exampleSite/config.toml` file so that we can see a working example on our netlify preview

Currently it looks like this:

![image](https://user-images.githubusercontent.com/5863972/211343392-2a3a8f7c-8624-4def-b46c-8732758288e7.png)

2023-02-01 10:55 UTC, 526avijitgupta commented
@azplanlos Any updates here?

2023-03-14 16:12 UTC, 526avijitgupta commented
Closing. Please reopen @azplanlos if there are any updates

2023-03-14 16:12 UTC, closed without merging

2023-06-11 09:32 UTC, azplanlos commented
Sorry, didn't see your messages. I will do the changes and provide an update.